name: simple-lua-tests
run-name: ${{ github.actor }} running tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install -y lua5.4
      - run: make test
      - run: lua example.lua
